1. Pandas DataFrame
2. Pandas Series
3. Pandas Basic Operation

In [2]:
import numpy as np
import pandas as pd

In [3]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
# create a dataframe
pd.DataFrame(data=np.arange(0,20).reshape(5,4),columns=['A','B','C','D'])

A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [9]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column A','Column B','Column C','Column D'])

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df

Column A  Column B  Column C  Column D
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [14]:
df.head(4)

Column A  Column B  Column C  Column D
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15

In [15]:
df.tail(3)

Column A  Column B  Column C  Column D
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [17]:
df.describe()

Column A   Column B   Column C   Column D
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [23]:
df[['Column A','Column B','Column C']]

Column A  Column B  Column C
Row1         0         1         2
Row2         4         5         6
Row3         8         9        10
Row4        12        13        14
Row5        16        17        18

In [24]:
type(df[['Column A','Column B','Column C']])

pandas.core.frame.DataFrame

In [25]:
df['Column A']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column A, dtype: int64

In [26]:
type(df['Column A'])

pandas.core.series.Series

In [27]:
df

Column A  Column B  Column C  Column D
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [28]:
df.loc[["Row1","Row3"]]

Column A  Column B  Column C  Column D
Row1         0         1         2         3
Row3         8         9        10        11

In [29]:
type(df.loc[["Row1","Row3"]])

pandas.core.frame.DataFrame

In [32]:
df.iloc[2:4,1:3]

Column B  Column C
Row3         9        10
Row4        13        14

In [33]:
df.iloc[0:3,:]

Column A  Column B  Column C  Column D
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11

In [34]:
df.iloc[0:3,:2]

Column A  Column B
Row1         0         1
Row2         4         5
Row3         8         9

In [35]:
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [47]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4],[5,4,3]],index=['Row1','Row2','Row3'],columns=['Column1','Column2','Column3'])

In [48]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [49]:
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False
Row3    False    False    False

In [50]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [51]:
df.isna().sum() 

Column1    0
Column2    1
Column3    0
dtype: int64

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Row1 to Row3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Column1  3 non-null      int64  
 1   Column2  2 non-null      float64
 2   Column3  3 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 96.0+ bytes


In [53]:
df['Column1'].value_counts()

Column1
1    2
5    1
Name: count, dtype: int64

In [54]:
df['Column1'].unique()

array([1, 5])

In [55]:
df['Column1'].nunique()

2

In [56]:
df1=pd.DataFrame({'A':[1,2,3],'B':[1,1,1]})
df1

A  B
0  1  1
1  2  1
2  3  1

In [59]:
df1['B'].unique()

array([1])

In [63]:
df1.nunique(axis=0) #axis=0 means Column unique values and axis=1 rows unique values

A    3
B    1
dtype: int64

In [64]:
df1.nunique(axis=1)

0    1
1    2
2    2
dtype: int64

In [65]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column A','Column B','Column C','Column D'])

In [66]:
df.head()

Column A  Column B  Column C  Column D
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [68]:
df['Column B']>5

Row1    False
Row2    False
Row3     True
Row4     True
Row5     True
Name: Column B, dtype: bool

In [69]:
df[df['Column B']>5]

Column A  Column B  Column C  Column D
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [74]:
df.to_csv('abcd.csv',index=False)

In [75]:
df1=pd.read_csv('abcd.csv')

In [76]:
df1.head()

Column A  Column B  Column C  Column D
0         0         1         2         3
1         4         5         6         7
2         8         9        10        11
3        12        13        14        15
4        16        17        18        19

In [77]:
df.to_json('abcde.json')

In [ ]:
pd.read_json('abcde.json')

Column A  Column B  Column C  Column D
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [82]:
data='{"Employee_name":"Amit","Email":"amit@gmail.com","Job_profile":[{"Title":"Data Science","Role":"Machine Learning Engineer"}]}'

In [83]:
data

'{"Employee_name":"Amit","Email":"amit@gmail.com","Job_profile":[{"Title":"Data Science","Role":"Machine Learning Engineer"}]}'

In [84]:
type(data)

str

In [86]:
df2=pd.read_json(data)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13064\1885955783.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df2=pd.read_json(data)


In [87]:
df2['Salary']=100

In [88]:
df2

Employee_name           Email  \
0          Amit  amit@gmail.com   

                                         Job_profile  Salary  
0  {'Title': 'Data Science', 'Role': 'Machine Lea...     100

In [89]:
df2['Job_profile']

0    {'Title': 'Data Science', 'Role': 'Machine Lea...
Name: Job_profile, dtype: object

In [90]:
df2

Employee_name           Email  \
0          Amit  amit@gmail.com   

                                         Job_profile  Salary  
0  {'Title': 'Data Science', 'Role': 'Machine Lea...     100

In [93]:
df2['Job_profile'][0]['Role']

'Machine Learning Engineer'

In [94]:
pd.read_json(data,orient='records')

C:\Users\DELL\AppData\Local\Temp\ipykernel_13064\2317705276.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data,orient='records')


Employee_name           Email  \
0          Amit  amit@gmail.com   

                                         Job_profile  
0  {'Title': 'Data Science', 'Role': 'Machine Lea...

In [95]:
pd.read_json(data,orient='index')

C:\Users\DELL\AppData\Local\Temp\ipykernel_13064\131370662.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(data,orient='index')


0
Employee_name                                               Amit
Email                                             amit@gmail.com
Job_profile    [{'Title': 'Data Science', 'Role': 'Machine Le...

In [ ]:
import pandas as pd
df=pd.DataFrame([['a','b'],['c','d']],index=['row1','row2'],columns=['col 1','col 2'])

In [96]:
df

Column A  Column B  Column C  Column D
Row1         0         1         2         3
Row2         4         5         6         7
Row3         8         9        10        11
Row4        12        13        14        15
Row5        16        17        18        19

In [97]:
df.to_json()

'{"Column A":{"Row1":0,"Row2":4,"Row3":8,"Row4":12,"Row5":16},"Column B":{"Row1":1,"Row2":5,"Row3":9,"Row4":13,"Row5":17},"Column C":{"Row1":2,"Row2":6,"Row3":10,"Row4":14,"Row5":18},"Column D":{"Row1":3,"Row2":7,"Row3":11,"Row4":15,"Row5":19}}'

In [98]:
df.to_json(orient='records')

'[{"Column A":0,"Column B":1,"Column C":2,"Column D":3},{"Column A":4,"Column B":5,"Column C":6,"Column D":7},{"Column A":8,"Column B":9,"Column C":10,"Column D":11},{"Column A":12,"Column B":13,"Column C":14,"Column D":15},{"Column A":16,"Column B":17,"Column C":18,"Column D":19}]'

In [99]:
df.to_json(orient='columns')

'{"Column A":{"Row1":0,"Row2":4,"Row3":8,"Row4":12,"Row5":16},"Column B":{"Row1":1,"Row2":5,"Row3":9,"Row4":13,"Row5":17},"Column C":{"Row1":2,"Row2":6,"Row3":10,"Row4":14,"Row5":18},"Column D":{"Row1":3,"Row2":7,"Row3":11,"Row4":15,"Row5":19}}'

In [100]:
df.to_json(orient="table")

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"Column A","type":"integer"},{"name":"Column B","type":"integer"},{"name":"Column C","type":"integer"},{"name":"Column D","type":"integer"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"Row1","Column A":0,"Column B":1,"Column C":2,"Column D":3},{"index":"Row2","Column A":4,"Column B":5,"Column C":6,"Column D":7},{"index":"Row3","Column A":8,"Column B":9,"Column C":10,"Column D":11},{"index":"Row4","Column A":12,"Column B":13,"Column C":14,"Column D":15},{"index":"Row5","Column A":16,"Column B":17,"Column C":18,"Column D":19}]}'